Bump Ruby to 3.1.3
Capybara is upgraded to work around the following error:

```
$ rake
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
rake aborted!
LoadError: cannot load such file -- matrix
/Users/jakob/.rvm/gems/ruby-3.1.3/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/Users/jakob/.rvm/gems/ruby-3.1.3/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/Users/jakob/.rvm/gems/ruby-3.1.3/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:332:in `block in require'
/Users/jakob/.rvm/gems/ruby-3.1.3/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/Users/jakob/.rvm/gems/ruby-3.1.3/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:332:in `require'
/Users/jakob/.rvm/gems/ruby-3.1.3/gems/capybara-3.33.0/lib/capybara/queries/selector_query.rb:3:in `<main>'
```